In [84]:
from torchvision import datasets
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score
import torch.utils.data as DATA
import numpy as np


In [85]:
Data_mnist = datasets.MNIST('data',download ='true')

In [86]:
train_set, test_set = DATA.random_split(Data_mnist, [36000, 24000])

In [87]:
train_set=np.array(train_set)
test_set=np.array(test_set)

<ipython-input-87-7da07fec6596>:1: FutureWarning: The input object of type 'Image' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Image', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  train_set=np.array(train_set)
<ipython-input-87-7da07fec6596>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  train_set=np.array(train_set)
<ipython-input-87-7da07fec6596>:2: FutureWarning: The input object of type 'Image' is an array-like implementing one of the corresponding protocols 

In [88]:
train_x=train_set[:,0]
train_y=train_set[:,1]
train_y=train_y.astype('int')
train_x=np.stack(train_x)
train_x=train_x.reshape((train_x.shape[0],-1))


In [89]:
test_x=test_set[:,0]
test_y=test_set[:,1]
test_y=test_y.astype('int')
test_x=np.stack(test_x)
test_x=test_x.reshape((test_x.shape[0],-1))


In [90]:
knn = KNeighborsClassifier(n_neighbors = 10)

In [91]:
knn.fit(train_x, train_y)

KNeighborsClassifier(n_neighbors=10)

In [92]:
from sklearn.model_selection import GridSearchCV
nnb = [ 3, 5,7, 10] 
knn = KNeighborsClassifier()
grid = GridSearchCV(knn, param_grid = {'n_neighbors': nnb}, cv=10)
grid.fit(train_x, train_y)

best_cv_err = 1 - grid.best_score_
best_n_neighbors = grid.best_estimator_.n_neighbors
print(best_cv_err, best_n_neighbors)

0.03213888888888883 3


In [93]:
knn = KNeighborsClassifier(n_neighbors = best_n_neighbors).fit(train_x, train_y)

In [94]:
%%time
test_y_predict=knn.predict(test_x)

Wall time: 1min 15s


In [95]:
err_test  = np.mean(test_y  != test_y_predict)
err_test

0.03145833333333333

In [96]:
print(accuracy_score(test_y,test_y_predict))

0.9685416666666666


In [97]:
from sklearn.metrics import f1_score
print(f1_score(test_y,test_y_predict,average='macro'))

0.9683585146537468


In [98]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(test_y, test_y_predict))

[[2374    1    0    0    1    3    4    0    1    2]
 [   2 2644    4    1    2    0    1    7    0    2]
 [  16   34 2266    8    5    1    4   32    2    0]
 [   1    6   15 2409    0   21    2   17    8    4]
 [   2   19    2    0 2326    0    8    9    0   47]
 [  10    4    1   28    5 2033   30    4    2    8]
 [  10    6    0    0    2    7 2314    0    1    0]
 [   3   22   10    1   10    0    0 2389    1   21]
 [   9   28   11   41   13   44    8    5 2184   24]
 [   5    6    3   23   21    3    2   27    2 2306]]
